string $window = `window -title "Welcome Message" -widthHeight 270 55`;
columnLayout -adjustableColumn true;
       rowLayout -nc 2 -ad2 2;
       		text -label "Insert name here: " -align "left";
       		string $text = `textField`;
       		setParent..;
       button -label "Ok" -command "Welcome_mess(`textField -q -tx $text`)";
setParent ..;
showWindow $window;

proc Welcome_mess(string $name){
	print("Welcome " +$name+ "\n");
}
